language: csharp
solution: Simple.Uri.sln
mono: none
dist: bionic
dotnet: 3.1.101
before_install:
- bash ./tools/travis-ci-install-sonar.sh
install:
  - dotnet restore
script:
- bash ./tools/travis-ci-build.sh
